service: clean-arch-sls

frameworkVersion: "3"

useDotenv: true

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1

custom:
  functionsDir: src/4-framework/functions
  serverless-offline:
    httpPort: 3333
  webpack:
    webpackConfig: "webpack.config.js"
    includeModules:
      forceInclude:
        # force include of your db drivers here
        - mysql2
    excludeFiles: tests/**

plugins:
  - serverless-webpack
  - serverless-offline

functions:
  - ${file(${self:custom.functionsDir}/roles/roles.yml)}
  - ${file(${self:custom.functionsDir}/users/users.yml)}
