service: clean-arch-sls

frameworkVersion: "3"

useDotenv: true

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  iam:
    role:
      statements: ${file(./devops/resources/iam.role.yml)}

custom:
  dbReadCapacityUnits: 1
  dbWriteCapacityUnits: 1
  functionsDir: src/4-framework/functions
  serverless-offline:
    httpPort: 3333
  webpack:
    webpackConfig: "webpack.config.js"

resources:
  - ${file(./devops/resources/dynamo.yml)}

plugins:
  - serverless-webpack
  - serverless-offline

functions:
  - ${file(${self:custom.functionsDir}/product/products.yml)}
