service: clean-arch-sls

frameworkVersion: "3"

useDotenv: true

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:GetItem
            - dynamodb:PutItem
          Resource: "*"

custom:
  dbReadCapacityUnits: 1
  dbWriteCapacityUnits: 1
  rolesTable: Roles
  usersTable: Users
  functionsDir: src/4-framework/functions
  serverless-offline:
    httpPort: 3333
  webpack:
    webpackConfig: "webpack.config.js"
    includeModules:
      forceInclude:
        # force include of your db drivers here
        - mysql2
    excludeFiles: tests/**

resources:
  Resources:
    RolesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: Users
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: N
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: ${self:custom.dbReadCapacityUnits}
          WriteCapacityUnits: ${self:custom.dbWriteCapacityUnits}
    UsersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: Roles
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: N
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: ${self:custom.dbReadCapacityUnits}
          WriteCapacityUnits: ${self:custom.dbWriteCapacityUnits}

plugins:
  - serverless-webpack
  - serverless-offline

functions:
  - ${file(${self:custom.functionsDir}/roles/roles.yml)}
  - ${file(${self:custom.functionsDir}/users/users.yml)}
